import React, { useState, useEffect, useRef, useCallback } from "react";

const TICKER_SEED = [
  { id: "AH-2291", initials: "J.M.", source: "LinkedIn", role: "Product Designer", status: "received" },
  { id: "AH-2292", initials: "R.K.", source: "Indeed", role: "Operations Lead", status: "received" },
  { id: "AH-2293", initials: "S.O.", source: "WhatsApp", role: "Sales Manager", status: "received" },
  { id: "AH-2294", initials: "T.A.", source: "Direct link", role: "Backend Engineer", status: "received" },
  { id: "AH-2295", initials: "D.N.", source: "LinkedIn", role: "Marketing Director", status: "received" },
];

const STATUS_SEQUENCE = ["received", "screening", "ranked"];
const STATUS_LABEL = {
  received: "RECEIVED",
  screening: "SCREENING",
  ranked: "RANKED",
};

const SUPPORTED_ROLES = [
  { title: "Operations & Logistics", desc: "Evaluate problem-solving, project oversight, and workflow optimization skills.", tag: "OPS & LOGISTICS" },
  { title: "Sales & Revenue", desc: "Filter quotas met, CRM experience, and deal negotiation capability automatically.", tag: "SALES & REVENUE" },
  { title: "Design & Product", desc: "Review portfolio highlights, product thinking, and user testing experience.", tag: "PRODUCT & CREATIVE" },
  { title: "Software & Tech", desc: "Analyze tech stack alignment, system architecture familiarity, and project history.", tag: "ENGINEERING" },
  { title: "Marketing & Growth", desc: "Screen campaign metrics, channel performance, and copy writing portfolios.", tag: "MARKETING" },
  { title: "People & HR", desc: "Identify talent acquisition experience, policy management, and team leadership.", tag: "HUMAN RESOURCES" },
];

const FAQS = [
  {
    q: "How does the single manifest solve scattered inboxes?",
    a: "Instead of logging into four job boards, two email accounts, and three agency portals, AvenHire generates one universal application link. Every response flows into a unified manifest automatically."
  },
  {
    q: "Is AvenHire designed only for software developer roles?",
    a: "Not at all. AvenHire is built for every department—from Operations and Marketing to Sales and Engineering."
  },
  {
    q: "Does the AI replace human hiring decisions?",
    a: "No. AvenHire acts as an automated sorting office. It organizes, summarizes, and ranks candidates so your team can make fast, informed decisions."
  },
  {
    q: "Where can I post the job link generated by AvenHire?",
    a: "Anywhere you connect with talent: LinkedIn, Indeed, email newsletters, WhatsApp groups, or career portals."
  }
];

function useReveal() {
  const ref = useRef(null);
  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting) {
            setVisible(true);
            obs.unobserve(el);
          }
        });
      },
      { threshold: 0.1 }
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, []);
  return [ref, visible];
}

function Reveal({ children, delay = 0, className = "" }) {
  const [ref, visible] = useReveal();
  return (
    <div
      ref={ref}
      className={`transition-all duration-700 ease-out transform ${
        visible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-5"
      } ${className}`}
      style={{ transitionDelay: `${delay}ms` }}
    >
      {children}
    </div>
  );
}

function Stamp({ status }) {
  const styles = {
    received: "text-[#55534A] border-[#55534A] bg-transparent",
    screening: "text-[#B8860B] border-[#B8860B] bg-amber-50",
    ranked: "text-[#1F5D50] border-[#1F5D50] bg-[#E0ECE8]",
  };

  return (
    <span className={`font-mono text-[10px] tracking-wider px-2 py-0.5 border text-center font-medium ${styles[status]}`}>
      {STATUS_LABEL[status]}
    </span>
  );
}

function ManifestTicker() {
  const [entries, setEntries] = useState(TICKER_SEED);

  useEffect(() => {
    const interval = setInterval(() => {
      setEntries((prev) =>
        prev.map((entry) => {
          const idx = STATUS_SEQUENCE.indexOf(entry.status);
          const next = STATUS_SEQUENCE[(idx + 1) % STATUS_SEQUENCE.length];
          return { ...entry, status: next };
        })
      );
    }, 2200);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="bg-[#DAD8CB] border border-[#1B1B16] shadow-[inset_1px_1px_0px_rgba(255,255,255,0.6),3px_3px_0px_rgba(27,27,22,0.15)] w-full max-w-3xl mx-auto overflow-hidden">
      <div className="grid grid-cols-2 md:grid-cols-3 items-center px-4 py-3 border-b border-[#1B1B16] font-mono text-xs tracking-wider text-[#55534A] bg-[#1F5D50]/10">
        <span>MANIFEST</span>
        <span className="hidden md:block text-center">POSTING · All Departments</span>
        <span className="text-right text-[#1F5D50] font-semibold">LIVE UPDATING</span>
      </div>
      <div className="divide-y divide-[#C9C6B8]">
        {entries.map((entry) => (
          <div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-5 items-center gap-2 px-4 py-3 text-xs sm:text-sm" key={entry.id}>
            <span className="font-mono text-[#55534A] text-xs">{entry.id}</span>
            <span className="font-medium text-[#1B1B16]">{entry.initials}</span>
            <span className="font-medium text-[#1B1B16] truncate">{entry.role}</span>
            <span className="hidden sm:inline text-[#55534A] text-xs">{entry.source}</span>
            <div className="text-right sm:text-left">
              <Stamp status={entry.status} />
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

const STEPS = [
  {
    code: "01",
    title: "Define the job, get one universal link",
    body: "Create your requirement once inside AvenHire for any role—Operations, Marketing, Sales, or Tech. Generate a single link for applicants everywhere.",
  },
  {
    code: "02",
    title: "Post that link anywhere candidates hang out",
    body: "Share on LinkedIn, Indeed, WhatsApp groups, or direct emails. Every channel routes candidate data back to your single master source.",
  },
  {
    code: "03",
    title: "Applications land in one organized manifest",
    body: "No more scattered inboxes, lost PDF attachments, or missing tabs. Every candidate submission streams into one real-time ledger.",
  },
  {
    code: "04",
    title: "Automated AI screening & summarization",
    body: "Resumes are evaluated against your specific criteria, summarized into readable insights, and assigned an objective fit score.",
  },
  {
    code: "05",
    title: "Review your ranked shortlist in minutes",
    body: "Filter by rank, inspect candidate strengths and gaps, and move directly to interview scheduling without inbox fatigue.",
  },
];

const COMPARE_ROWS = [
  ["Where candidates apply", "5 different job boards and inbox portals", "One universal link shared anywhere"],
  ["Application storage", "Scattered across inboxes & spreadsheets", "One unified, auto-updating manifest"],
  ["Screening process", "Opening and reading PDFs manually", "AI reads, summarizes, and scores every applicant"],
  ["Role support", "Keywords tuned strictly for tech roles", "Tailored evaluation for Ops, Sales, Marketing & Tech"],
  ["Time to shortlist", "Days spent reading unorganized submissions", "Minutes after submissions arrive in the manifest"],
];

function LiveDemo() {
  const [jobReq, setJobReq] = useState(
    "Operations & Logistics Manager, 3+ years experience. Must have experience managing supply chain workflows, vendor negotiations, and team scheduling. Strong data analysis skills in Excel or SQL required."
  );
  const [resume, setResume] = useState(
    "Marcus Vance. 4 years as Operations Coordinator at a regional distribution hub. Managed vendor contracts, improved fulfillment turnaround by 22%, proficient in Excel and Tableau. Supervised a team of 8 logistics associates."
  );
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");

  const run = useCallback(async () => {
    if (!jobReq.trim() || !resume.trim()) {
      setError("Add both a job requirement and a resume before running the screen.");
      return;
    }
    setError("");
    setLoading(true);
    setResult(null);
    try {
      const response = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          model: "claude-sonnet-4-6",
          max_tokens: 1000,
          system:
            'Return ONLY a JSON object, no markdown fences, no preamble, no trailing text. Shape: {"score": <integer 0-100>, "summary": "<2-3 plain sentences on overall fit>", "highlights": ["<short strength>", "<short strength>"], "gaps": ["<short gap, or omit if none>"]}',
          messages: [
            {
              role: "user",
              content: `Job requirements:\n${jobReq}\n\nCandidate resume:\n${resume}`,
            },
          ],
        }),
      });
      const data = await response.json();
      const text = (data.content || [])
        .map((block) => block.text || "")
        .join("")
        .replace(/```json|```/g, "")
        .trim();
      const parsed = JSON.parse(text);
      setResult(parsed);
    } catch (err) {
      setError("Screening failed to complete. Please try again.");
    } finally {
      setLoading(false);
    }
  }, [jobReq, resume]);

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
      <div className="flex flex-col gap-4">
        <div>
          <label className="font-mono text-xs text-[#55534A] uppercase tracking-wider block mb-1">
            Job requirements (Any department)
          </label>
          <textarea
            className="w-full p-3 bg-[#E3E1D6] border border-[#1B1B16] shadow-[inset_2px_2px_3px_rgba(0,0,0,0.08)] font-sans text-sm text-[#1B1B16] focus:outline-none focus:ring-2 focus:ring-[#1F5D50]"
            value={jobReq}
            onChange={(e) => setJobReq(e.target.value)}
            rows={4}
          />
        </div>
        <div>
          <label className="font-mono text-xs text-[#55534A] uppercase tracking-wider block mb-1">
            Candidate profile / resume
          </label>
          <textarea
            className="w-full p-3 bg-[#E3E1D6] border border-[#1B1B16] shadow-[inset_2px_2px_3px_rgba(0,0,0,0.08)] font-sans text-sm text-[#1B1B16] focus:outline-none focus:ring-2 focus:ring-[#1F5D50]"
            value={resume}
            onChange={(e) => setResume(e.target.value)}
            rows={4}
          />
        </div>
        {error && <p className="text-[#A13D2D] text-xs font-medium">{error}</p>}
        <button
          className="w-full sm:w-auto self-start px-6 py-3 bg-[#1F5D50] hover:bg-[#123E35] text-white border border-[#123E35] font-medium text-sm transition-all shadow-[2px_2px_0px_rgba(27,27,22,0.2)] active:translate-x-[1px] active:translate-y-[1px]"
          onClick={run}
          disabled={loading}
        >
          {loading ? "Screening manifest entry..." : "Run screen on manifest"}
        </button>
      </div>

      <div className="bg-[#DAD8CB] p-5 border border-[#1B1B16] border-t-4 border-t-[#1F5D50] shadow-[3px_3px_0px_rgba(27,27,22,0.15)] min-h-[300px]">
        <div className="flex justify-between items-center font-mono text-xs text-[#55534A] pb-3 border-b border-[#1B1B16] mb-4">
          <span>MANIFEST ENTRY</span>
          <span>AH-DEMO-2026</span>
        </div>

        {loading && (
          <div className="space-y-3 animate-pulse">
            <div className="h-4 bg-[#C9C6B8] w-1/3"></div>
            <div className="h-4 bg-[#C9C6B8] w-full"></div>
            <div className="h-4 bg-[#C9C6B8] w-5/6"></div>
            <div className="h-4 bg-[#C9C6B8] w-2/3"></div>
          </div>
        )}

        {!loading && !result && (
          <p className="text-[#55534A] text-sm italic">
            Run the screen to see how candidate applications land, summarize, and score directly inside the manifest.
          </p>
        )}

        {!loading && result && (
          <div className="space-y-4">
            <div className="flex items-baseline gap-3">
              <span className="font-serif text-4xl sm:text-5xl font-semibold text-[#1F5D50]">{result.score}</span>
              <span className="font-mono text-xs text-[#55534A]">FIT SCORE / 100</span>
            </div>
            <p className="text-sm text-[#1B1B16] leading-relaxed">{result.summary}</p>
            {Array.isArray(result.highlights) && result.highlights.length > 0 && (
              <div>
                <p className="font-mono text-xs text-[#123E35] font-semibold uppercase tracking-wider mb-1">Key Strengths</p>
                <ul className="list-disc list-inside text-sm text-[#1B1B16] space-y-1">
                  {result.highlights.map((h, i) => (
                    <li key={i}>{h}</li>
                  ))}
                </ul>
              </div>
            )}
            {Array.isArray(result.gaps) && result.gaps.length > 0 && (
              <div>
                <p className="font-mono text-xs text-[#123E35] font-semibold uppercase tracking-wider mb-1">Requirements Gaps</p>
                <ul className="list-disc list-inside text-sm text-[#1B1B16] space-y-1">
                  {result.gaps.map((g, i) => (
                    <li key={i}>{g}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

export default function AvenHireLanding() {
  const [email, setEmail] = useState("");
  const [reserved, setReserved] = useState(false);
  const [emailError, setEmailError] = useState("");
  const [openFaq, setOpenFaq] = useState(null);

  const submitWaitlist = (e) => {
    e.preventDefault();
    if (!/^\S+@\S+\.\S+$/.test(email)) {
      setEmailError("Please enter a valid email address.");
      return;
    }
    setEmailError("");
    setReserved(true);
  };

  return (
    <div className="min-h-screen bg-[#E3E1D6] text-[#1B1B16] font-sans antialiased selection:bg-[#1F5D50] selection:text-white">
      {/* NAVIGATION */}
      <nav className="flex flex-wrap items-center justify-between px-6 sm:px-10 py-5 border-b border-[#C9C6B8]">
        <div className="font-serif text-2xl font-semibold tracking-tight">
          Aven<span className="text-[#1F5D50]">Hire</span>
        </div>
        <div className="hidden md:flex items-center gap-8 text-sm font-medium text-[#55534A]">
          <a href="#manifest-concept" className="hover:text-[#1F5D50] transition-colors">The Manifest</a>
          <a href="#roles" className="hover:text-[#1F5D50] transition-colors">Departments</a>
          <a href="#how" className="hover:text-[#1F5D50] transition-colors">How it works</a>
          <a href="#demo" className="hover:text-[#1F5D50] transition-colors">Live Demo</a>
        </div>
        <a
          href="#waitlist"
          className="px-4 py-2 text-sm font-medium text-white bg-[#1F5D50] hover:bg-[#123E35] border border-[#123E35] transition-all shadow-[2px_2px_0px_rgba(27,27,22,0.2)] active:translate-x-[1px] active:translate-y-[1px]"
        >
          Get Early Access
        </a>
      </nav>

      {/* HERO SECTION */}
      <section className="max-w-6xl mx-auto px-6 sm:px-10 pt-16 pb-12 sm:pt-20 sm:pb-16">
        <Reveal>
          <span className="font-mono text-xs tracking-widest text-[#123E35] border border-[#1F5D50] bg-[#E0ECE8] px-3.5 py-1.5 inline-block mb-6 font-medium shadow-[inset_1px_1px_0px_rgba(255,255,255,0.7)]">
            APPLICATION MANIFEST · NO. 000-1
          </span>
        </Reveal>
        <Reveal delay={80}>
          <h1 className="font-serif text-4xl sm:text-6xl lg:text-7xl font-normal tracking-tight leading-[1.1] max-w-4xl">
            One link. Every channel. <br className="hidden sm:inline" />
            <span className="text-[#1F5D50] font-medium">All applications land in one manifest.</span>
          </h1>
        </Reveal>
        <Reveal delay={160}>
          <p className="text-base sm:text-lg text-[#55534A] max-w-2xl mt-6 mb-8 leading-relaxed">
            Stop checking four job boards, three email inboxes, and endless spreadsheets. AvenHire generates one master link for any job role. Every application flows into a single, organized manifest—automatically summarized and ranked by AI.
          </p>
        </Reveal>
        <Reveal delay={220}>
          <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-4">
            <a
              href="#waitlist"
              className="px-6 py-3.5 text-center font-medium text-white bg-[#1F5D50] hover:bg-[#123E35] border border-[#123E35] shadow-[2px_2px_0px_rgba(27,27,22,0.2)] transition-all"
            >
              Get Early Access
            </a>
            <a
              href="#demo"
              className="px-6 py-3.5 text-center font-medium text-[#1B1B16] hover:text-[#1F5D50] underline underline-offset-4 transition-colors"
            >
              Try the Live Manifest ↓
            </a>
          </div>
        </Reveal>
        <Reveal delay={300} className="mt-12">
          <ManifestTicker />
        </Reveal>
      </section>

      {/* MANIFEST FOCUS CONCEPT SECTION */}
      <section className="border-t border-[#C9C6B8] bg-[#DAD8CB] py-16" id="manifest-concept">
        <div className="max-w-6xl mx-auto px-6 sm:px-10">
          <Reveal>
            <div className="max-w-3xl">
              <span className="font-mono text-xs text-[#123E35] font-semibold uppercase tracking-wider block mb-2">
                THE SINGLE MANIFEST ADVANTAGE
              </span>
              <h2 className="font-serif text-3xl sm:text-4xl font-normal leading-tight text-[#1B1B16]">
                Say goodbye to scattered inboxes and lost applications.
              </h2>
            </div>
          </Reveal>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-12">
            <Reveal delay={0}>
              <div className="bg-[#E3E1D6] p-6 border border-[#1B1B16] border-t-4 border-t-[#1F5D50] shadow-[3px_3px_0px_rgba(27,27,22,0.15)] h-full flex flex-col justify-between">
                <div>
                  <div className="font-mono text-2xl font-bold text-[#1F5D50] mb-2">01</div>
                  <h3 className="font-serif text-xl font-medium mb-2">Universal Collection</h3>
                  <p className="text-sm text-[#55534A] leading-relaxed">
                    Paste your single AvenHire application link on LinkedIn, Indeed, WhatsApp, or carrier sites. All submissions flow back into one entry ledger.
                  </p>
                </div>
              </div>
            </Reveal>

            <Reveal delay={100}>
              <div className="bg-[#E3E1D6] p-6 border border-[#1B1B16] border-t-4 border-t-[#1F5D50] shadow-[3px_3px_0px_rgba(27,27,22,0.15)] h-full flex flex-col justify-between">
                <div>
                  <div className="font-mono text-2xl font-bold text-[#1F5D50] mb-2">02</div>
                  <h3 className="font-serif text-xl font-medium mb-2">Instant Summaries</h3>
                  <p className="text-sm text-[#55534A] leading-relaxed">
                    As each submission hits the manifest, AI scans candidate qualifications, extracts key experience highlights, and tags immediate fit gaps.
                  </p>
                </div>
              </div>
            </Reveal>

            <Reveal delay={200}>
              <div className="bg-[#E3E1D6] p-6 border border-[#1B1B16] border-t-4 border-t-[#1F5D50] shadow-[3px_3px_0px_rgba(27,27,22,0.15)] h-full flex flex-col justify-between">
                <div>
                  <div className="font-mono text-2xl font-bold text-[#1F5D50] mb-2">03</div>
                  <h3 className="font-serif text-xl font-medium mb-2">Automated Ranking</h3>
                  <p className="text-sm text-[#55534A] leading-relaxed">
                    Candidates are ranked transparently in real-time. Spend your day reaching out to top talent instead of opening scattered PDF attachments.
                  </p>
                </div>
              </div>
            </Reveal>
          </div>
        </div>
      </section>

      {/* DEPARTMENT COVERAGE SECTION */}
      <section className="max-w-6xl mx-auto px-6 sm:px-10 py-16 border-t border-[#C9C6B8]" id="roles">
        <Reveal>
          <div className="flex flex-col md:flex-row md:items-baseline justify-between mb-10 gap-2">
            <h2 className="font-serif text-3xl sm:text-4xl">Built for every hiring department</h2>
            <span className="font-mono text-xs text-[#123E35] tracking-wider font-semibold">
              CROSS-FUNCTIONAL COVERAGE
            </span>
          </div>
        </Reveal>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {SUPPORTED_ROLES.map((r, i) => (
            <Reveal key={r.title} delay={i * 60}>
              <div className="bg-[#DAD8CB] p-6 border border-[#1B1B16] border-l-4 border-l-[#1F5D50] shadow-[3px_3px_0px_rgba(27,27,22,0.15)] h-full flex flex-col justify-between">
                <div>
                  <span className="font-mono text-[11px] font-semibold text-[#123E35] tracking-wider block mb-2">
                    {r.tag}
                  </span>
                  <h3 className="font-serif text-xl font-medium mb-2">{r.title}</h3>
                  <p className="text-sm text-[#55534A] leading-relaxed">{r.desc}</p>
                </div>
              </div>
            </Reveal>
          ))}
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section className="max-w-6xl mx-auto px-6 sm:px-10 py-16 border-t border-[#C9C6B8]" id="how">
        <Reveal>
          <div className="flex flex-col md:flex-row md:items-baseline justify-between mb-10 gap-2">
            <h2 className="font-serif text-3xl sm:text-4xl">How a posting becomes a shortlist</h2>
            <span className="font-mono text-xs text-[#123E35] tracking-wider font-semibold">
              5 SIMPLE STEPS
            </span>
          </div>
        </Reveal>
        <div className="border-t border-[#1B1B16] divide-y divide-[#C9C6B8]">
          {STEPS.map((s, i) => (
            <Reveal key={s.code} delay={i * 60}>
              <div className="grid grid-cols-1 md:grid-cols-[80px_1fr] gap-4 md:gap-8 py-6 items-start">
                <span className="font-mono text-base font-semibold text-[#1F5D50]">{s.code}</span>
                <div>
                  <h3 className="font-serif text-xl font-medium mb-1.5">{s.title}</h3>
                  <p className="text-sm sm:text-base text-[#55534A] max-w-2xl leading-relaxed">{s.body}</p>
                </div>
              </div>
            </Reveal>
          ))}
        </div>
      </section>

      {/* LIVE DEMO */}
      <section className="max-w-6xl mx-auto px-6 sm:px-10 py-16 border-t border-[#C9C6B8]" id="demo">
        <Reveal>
          <div className="flex flex-col md:flex-row md:items-baseline justify-between mb-10 gap-2">
            <h2 className="font-serif text-3xl sm:text-4xl">Test the manifest screening live</h2>
            <span className="font-mono text-xs text-[#123E35] tracking-wider font-semibold">
              REAL-TIME AI EVALUATION
            </span>
          </div>
        </Reveal>
        <Reveal delay={100}>
          <LiveDemo />
        </Reveal>
      </section>

      {/* COMPARISON TABLE */}
      <section className="max-w-6xl mx-auto px-6 sm:px-10 py-16 border-t border-[#C9C6B8]">
        <Reveal>
          <div className="flex flex-col md:flex-row md:items-baseline justify-between mb-10 gap-2">
            <h2 className="font-serif text-3xl sm:text-4xl">What changes for your hiring team</h2>
            <span className="font-mono text-xs text-[#123E35] tracking-wider font-semibold">
              BEFORE & AFTER
            </span>
          </div>
        </Reveal>
        <Reveal delay={100}>
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse min-w-[600px]">
              <thead>
                <tr className="border-b border-[#1B1B16] font-mono text-xs text-[#55534A]">
                  <th className="py-3 px-4">TASK</th>
                  <th className="py-3 px-4">WITHOUT AVENHIRE</th>
                  <th className="py-3 px-4 text-[#123E35]">WITH AVENHIRE</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#C9C6B8] text-sm">
                {COMPARE_ROWS.map((row, idx) => (
                  <tr key={idx} className="hover:bg-[#DAD8CB]/40 transition-colors">
                    <td className="py-4 px-4 font-medium text-[#1B1B16]">{row[0]}</td>
                    <td className="py-4 px-4 text-[#55534A]">{row[1]}</td>
                    <td className="py-4 px-4 font-semibold text-[#123E35]">{row[2]}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Reveal>
      </section>

      {/* FAQ SECTION */}
      <section className="max-w-6xl mx-auto px-6 sm:px-10 py-16 border-t border-[#C9C6B8]">
        <Reveal>
          <div className="flex flex-col md:flex-row md:items-baseline justify-between mb-10 gap-2">
            <h2 className="font-serif text-3xl sm:text-4xl">Frequently asked questions</h2>
            <span className="font-mono text-xs text-[#123E35] tracking-wider font-semibold">
              MANIFEST DETAILS
            </span>
          </div>
        </Reveal>
        <div className="space-y-4">
          {FAQS.map((faq, idx) => (
            <Reveal key={idx} delay={idx * 50}>
              <div className="bg-[#DAD8CB] border border-[#1B1B16] shadow-[2px_2px_0px_rgba(27,27,22,0.1)]">
                <button
                  className="w-full text-left p-5 flex justify-between items-center font-serif text-lg font-medium text-[#1B1B16]"
                  onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                >
                  <span>{faq.q}</span>
                  <span className="text-[#1F5D50] text-xl font-mono">{openFaq === idx ? "−" : "+"}</span>
                </button>
                {openFaq === idx && (
                  <div className="px-5 pb-5 text-sm text-[#55534A] leading-relaxed border-t border-[#C9C6B8] pt-3">
                    <p>{faq.a}</p>
                  </div>
                )}
              </div>
            </Reveal>
          ))}
        </div>
      </section>

      {/* WAITLIST CALLOUT */}
      <section className="max-w-6xl mx-auto px-6 sm:px-10 pb-16" id="waitlist">
        <Reveal>
          <div className="bg-[#123E35] text-[#E3E1D6] p-8 sm:p-12 border border-[#1B1B16] shadow-[4px_4px_0px_rgba(27,27,22,0.2)] flex flex-col md:flex-row items-start md:items-center justify-between gap-8">
            <div>
              <h2 className="font-serif text-3xl sm:text-4xl text-white">
                Ready for <span className="text-[#E0ECE8]">one manifest</span> to handle all applications?
              </h2>
              <p className="text-sm text-[#E0ECE8]/80 mt-2 max-w-md">
                Get early access to AvenHire and streamline your next hiring cycle.
              </p>
            </div>
            {!reserved ? (
              <form className="w-full md:w-auto flex flex-col sm:flex-row gap-2" onSubmit={submitWaitlist}>
                <input
                  type="email"
                  className="px-4 py-3 bg-white/10 border border-[#E3E1D6] text-white placeholder-[#C9C6B8] text-sm focus:outline-none focus:ring-2 focus:ring-[#E0ECE8]"
                  placeholder="name@company.com"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                />
                <button
                  type="submit"
                  className="px-6 py-3 bg-[#E3E1D6] hover:bg-white text-[#123E35] font-semibold text-sm transition-colors whitespace-nowrap"
                >
                  Reserve Spot
                </button>
                {emailError && <span className="text-red-300 text-xs mt-1 sm:hidden">{emailError}</span>}
              </form>
            ) : (
              <div className="font-mono text-xs border border-[#E3E1D6] px-4 py-3 text-white tracking-widest uppercase">
                RESERVED · ACCESS CODE SENT
              </div>
            )}
          </div>
        </Reveal>
      </section>

      {/* FOOTER */}
      <footer className="max-w-6xl mx-auto px-6 sm:px-10 py-8 border-t border-[#C9C6B8] flex flex-col sm:flex-row items-center justify-between gap-4 text-xs font-mono text-[#55534A]">
        <div className="font-serif text-base font-semibold text-[#1B1B16]">
          Aven<span className="text-[#1F5D50]">Hire</span>
        </div>
        <div>ONE MANIFEST · ALL APPLICATIONS</div>
        <div>© 2026 AVENHIRE INC.</div>
      </footer>
    </div>
  );
}